# Site
title: 小楚的知识库
subtitle: '储存自己的知识，不断向前'
description: '知识博客'
keywords:
author: 主理人：chuxuan
language: zh-CN
timezone: 'Asia/Shanghai'
# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://chuxuanknowledgebase.top/
root: /
permalink: :year/:month/:day/:hour-:minute-:second/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks


# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next


# Schemes
scheme: Muse
# scheme: Mist
# scheme: Pisces
# scheme: Gemini



# Creative Commons 4.0 International License.
# See: https://creativecommons.org/about/cclicenses/
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
# CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
creative_commons:
  license: by-nc-sa
  sidebar: true #侧边栏中的版权标识
  post: true #每篇文章底部都显示版权信息
  language:zh-CN


menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  #categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

# Enable / Disable menu icons / item badges.
menu_settings:
  icons: true
  badges: false


sidebar:
  # Sidebar Position.
  # position: left
  position: right



# Sidebar Display (only for Muse | Mist), available values:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically.
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  totally remove sidebar including sidebar toggle.
  display: always



# Sidebar Avatar
avatar:
  # Replace the default image and set the url here.
  url: /uploads/avatar.jpg #头像图片地址 
  # If true, the avatar will be dispalyed in circle.圆形选true 方形选false
  rounded: true
  # If true, the avatar will be rotated with the cursor.魔性转动，打开选true
  rotated: false



social:
  喜马拉雅FM(无):  
  新浪微博(无): 
  今日头条(无): 
  微信公众号(无): 
  知乎(无): 
  简书(无): 



# Blog rolls
links_settings:
  icon: fa fa-link
  title: 赞助商链接
  # Available values: block | inline
  layout: block

links:
  AK47突突突: 

reward_settings:
  # If true, a donate button will be displayed in every article by default.
  enable: true
  animation: false
  comment: Q：付钱的东西，做出来玩玩，别扫哦

reward:
  wechatpay: /images/wechatpay.png
  alipay: /images/alipay.png



# Subscribe through Telegram Channel, Twitter, etc.
# Usage: `Key: permalink || icon` (Font Awesome)
follow_me:
  微博: https://weibo.com/u/6106797403 || fab fa-weibo
  知乎: https://www.zhihu.com/people/xuan-xuan-hen-you-qu || fab fa-zhihu
  微信: https://mp.weixin.qq.com/s/-hUYR2dOofvEP0COu4e5Tw || fab fa-weixin


back2top:
  enable: true
  # Back to top in sidebar.
  sidebar: false
  # Scroll percent label in b2t button.
  scrollpercent: true


motion:
  enable: false
  async: false


