menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    音乐: /music/ || fas fa-music
    照片: /Gallery/ || fas fa-images
    电影: /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

highlight_copy: true
highlight_theme: pale night
highlight_shrink: true
code_word_wrap: true
highlight_height_limit: false # unit: px

social:
  fab fa-github: https://github.com/chunxuancao || Github
  fas fa-envelope: mailto:cao18373503328@outlook.com || Email

index_img: xxx.png
