title: chuxuan的知识库
subtitle: ''
description: '知识库'
keywords:
author: chuxuan
language: zh-CN
timezone: ''
# 基本信息配置

post_asset_folder: true
# 开启文章资源夹

url: https://chuxuanknowledgebase.top/
# 设置为自己的域名


theme: butterfly
# 设置自己的主题


